server:
  port: 9001

spring:
   application:
      name: API-GATEWAY SERVICE
      cloud:
        gateway:
         routes:
          - id: ADMIN-SERVICE
            uri: http://localhost:8080
            predicates:
              - Path=/admin/**
          - id: FARMER-SERVICE
            uri: http://localhost:8081
            predicates:
              - Path=/farmer/**
          - id: DEALER-SERVICE
            uri: http://localhost:8082
            predicates:
              - Path=/dealer/**
          - id: CROP-SERVICE
            uri: http://localhost:8084
            predicates:
              - Path=/crop/**





